### ISSUE TITLE
Add support for other ingress annotations

### ISSUE THREAD

**Issue by rajish** [loft-sh/loft#112]
The current ingress is tailored specifically for Nginx. In my case, I'd like to use AWS ALB which requires a lot of annotations to configure. To achieve it I had to hack the `ingress.yaml` like this:

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "loft.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- with .Values.ingress.annotations }}
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.clusterIssuer }}
  {{- end }}
```

Using `tpl (toYaml) .) $` allows to put template strings in the values file like:
```
      external-dns.alpha.kubernetes.io/hostname: "loft.{{ .Values.deploymentName }}.my-domain.com"
```
