### ISSUE TITLE
Can't go past the "Complete your profile" page

### ISSUE THREAD

**Issue by rajish** [loft-sh/loft#113]
Submitting the form on the "Complete your profile" page spins the "Finish" button indefinitely. The loft pod logs say:
```
loft-6b647d94dc-ld6tl manager 2021-05-02 12:47:41.819818 I | http: TLS handshake error from 127.0.0.1:57608: remote error: tls: unknown certificate
```
I have TLS disabled in the `values.yaml`:

```
# TLS configuration with a custom cert and key
# Make sure the secret exists prior to deploying loft,
# otherwise the loft pod will not be able to start
tls:
  enabled: false
  secret: loft-tls
  crtKey: tls.crt
  keyKey: tls.key

...
ingress:
...
  tls:
    enabled: false
    secret: tls-loft
    clusterIssuer: lets-encrypt-http-issuer
```
