### ISSUE TITLE
Install loft by Argo CD seems stucking in Syncing, except first time

### ISSUE THREAD

**Issue by yaosiang** [loft-sh/loft#153]
I am using OpenShift + Argo CD to install loft, the following is my Argo CD manifest. The manifest tells Argo CD to use helm to install loft and feeding some vaules to do customization.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loft
spec:
  destination:
    namespace: loft
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.loft.sh
    targetRevision: 1.15.0
    chart: loft
    helm:
      values: |
        ingress:
          enabled: false
  syncPolicy:
    syncOptions:
    - CreateNamespace=true 
    automated:
      prune: true
      selfHeal: true
```

It can be sync loft succssfully at first time.

But, after deleting all resource installed by loft, including loft-agent, APIService, CRD, RBAC...everything. It seems unable to sync loft again and Argo CD keep stucking in Syncing status.

Any suggestion or experience for how to install loft by Argo CD or any other GitOps tools?
