### ISSUE TITLE
Helm: Loft deadlocks install if transient failure

### ISSUE THREAD

**Issue by withinboredom** [loft-sh/loft#169]
During a loft installation via helm, there was a transient failure:

```
Error: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://nginx-ingress-nginx-controller-admission.ingress.svc:443/networking/v1/ingresses?timeout=10s": context deadline exceeded
```

Rerunning the helm command just ends up with this error:

```
Error: failed pre-install: warning: Hook pre-install loft/templates/admin/user.yaml failed: object is being deleted: users.storage.loft.sh "admin" already exists
```

which results in a single loft-agent pod, no other loft pods.

Here's the values for the helm chart fwiw:

```
    admin:
      create: true
      username: admin
      password: PASSWORD
    ingress:
      enabled: true
      name: loft-ingress
      host: DOMAIN
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      tls:
        enabled: true
        secret: tls-loft
```

`loft start` was able to resolve the issue.
