### ISSUE TITLE
Fails to sleep space consisting only of cronjobs

### ISSUE THREAD

**Issue by withinboredom** [loft-sh/loft#235]
With V3:

1. Create a space with only a CronJob.
2. Sleep the space
3. First time works, UI shows not sleeping
4. Try sleeping again, get an error with no details
5. CronJobs still run

**Comment by carlmontanari** [comment]
👋 hey, thanks for raising this!

I'm not sure I can repro, here's what I did, maybe you can tell me what im missing?

1. create a space
2. create a cronjob copy pasta from docs set for every 2 min

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

3. wait for it to run once just to make sure I didn't botch anything 😇 
4. sleep the space
5. wait for 2minutes 🕐 
6. nothing happened -- space stayed asleep and the pods didn't run or anything -- if I use the space's kubecontext to check pods or whatever (without prevent automatic wake up) the space wakes up though and the cron job starts doing its thing again)

If I do the same *with* automatic-wakeup prevented then that last point is the same (cron pods never run) minus the space waking up when I `k get pods` in that context.

Could you share maybe an example cron and/or screenshot of the error with no details so we can try to track down whatever is goin on?

Thanks!
