### ISSUE TITLE
Loft cannot be uninstalled

### ISSUE THREAD

**Issue by mausch** [loft-sh/loft#252]
Namespace won't delete, has status:

```
status:
  phase: Terminating
  conditions:
    - type: NamespaceDeletionDiscoveryFailure
      status: 'True'
      lastTransitionTime: '2023-10-20T11:18:14Z'
      reason: DiscoveryFailed
      message: >-
        Discovery failed for some groups, 1 failing: unable to retrieve the
        complete list of server APIs: cluster.loft.sh/v1: stale GroupVersion
        discovery: cluster.loft.sh/v1
```

Loft helm chart 3.2.4
Kubernetes 1.28 on EKS
