### ISSUE TITLE
apps installed from custom helm repo is not getting version updates

### ISSUE THREAD

**Issue by blairham** [loft-sh/loft#57]
When you have an app installed from a custom URL it does not get helm version updates.

for example:

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/07d03c1d-bc89-4d1f-beec-304737726c26/2dae409e-ded6-4c77-b1ae-ce42817d809a)

```
helm search repo spotinst
NAME                                           	CHART VERSION	APP VERSION	DESCRIPTION
spotinst/spotinst-kubernetes-cluster-controller	1.0.76       	1.0.67     	A Helm chart for Spotinst Kubernetes cluster co...
```

You can see here that the latest chart version if 1.0.76, however, Loft is not showing it as outdated nor as a selection in the dropdown menu.

**Comment by FabianKramm** [comment]
@blairham that is working as itended. Currently updates from a private repo are only supported if that private repo is in the list of app repos loft knows about. You can change the list of repos with the environment variable `APPSTORE_REPOS_URL` or `APPSTORE_REPOS_FILE` if its a file within the loft container. The repo file has the following format (check at https://raw.githubusercontent.com/loft-sh/loft/master/appstore/repos.yaml for the current repo file):

```yaml
sync:
  repos:
    - name: devspace
      url: https://charts.devspace.sh
    - name: stable
      url: https://kubernetes-charts.storage.googleapis.com
    - name: incubator
      url: https://kubernetes-charts-incubator.storage.googleapis.com
    - name: jfrog
      url: https://charts.jfrog.io
...
```

As soon as your private repo is part of this file, all the charts of the repo will also appear in the chart selector when you are adding a new app. If you only add your private repo it will not show any other charts anymore, so please be aware of that, you could just copy the file at https://raw.githubusercontent.com/loft-sh/loft/master/appstore/repos.yaml and add yours if you want to just add a single private repo.
