### ISSUE TITLE
helm stable repo in loft is using the now depricated url

### ISSUE THREAD

**Issue by blairham** [loft-sh/loft#72]
Currently, you can not update helm apps due to the now deprecated URL. According to [this article ](https://www.cncf.io/blog/2020/10/07/important-reminder-for-all-helm-users-stable-incubator-repos-are-deprecated-and-all-images-are-changing-location/) on November 13th, the old repos are now deprecated.

*Expected Results*
Installing/Upgrading an app through loft should continue to work.

**Comment by FabianKramm** [comment]
@blairham thanks for opening this issue! What is the error that you are receiving? Currently the stable repo is still listed in our app repo list, however we will remove that eventually. If you want to change the repository of an installed app, you can go to `Clusters` -> `Apps` and click on the `Show Yaml` button. Then change the repository URL in the spec section:

```yaml
apiVersion: cluster.loft.sh/v1
kind: HelmRelease
metadata:
  ...
spec:
  chart:
    name: docker-registry
    version: 1.9.6 <- Change this to the new version
    repoURL: 'https://kubernetes-charts.storage.googleapis.com' <- Change this URL to the new repo URL
status:
  ...
```

Then press update and loft will change the repo and version of the app. We cannot do this automatically since we don't know for each chart how the new repository is called, hence why you need to update this manually.
