### ISSUE TITLE
Browser error:  SEC_ERROR_REUSED_ISSUER_AND_SERIAL

### ISSUE THREAD

**Issue by RudyBone** [loft-sh/loft#79]
I am running air-gapped using the loft:1.3.0 image and the 1.2.1 chart.  

Install goes fine, both loft and kiosk pods are running.  I use the port-foward command and go to https://localhost:8080 in my firefox browser and I get the following message:

Error code: SEC_ERROR_REUSED_ISSUER_AND_SERIAL

I suspect this may have something to do with the self signed certs generated but don't know how to proceed.

Also I'd rather use https over an nginx-ingress controller but couldn't seem to get that working either

**Comment by LukasGentele** [comment]
@RudyBone You should be able to use HTTP instead of HTTPS when testing using port-forward. If you want to use an ingress controller, configure TLS in your ingress settings and point the ingress to the service `loft` on port 80 instead of port 443, so that Loft will not handle the SSL handshake but rather the ingress controller will manage the TLS entirely. Here is a sample ingress resource:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: loft-ingress
  namespace: loft
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: lets-encrypt-http-issuer            # in case you are using cert-manager to auto-generate the cert secret
    nginx.ingress.kubernetes.io/proxy-read-timeout: "43200"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "43200"
spec:
  rules:
  - host: loft.yourdomain.tld
    http:
      paths:
      - backend:
          serviceName: loft
          servicePort: 80
        path: /
  tls:
  - hosts:
    - loft.yourdomain.tld
    secretName: tls-loft
```

You can also create this ingress by configuring the appropriate values for the Loft helm chart: https://github.com/loft-sh/loft/blob/master/chart/values.yaml#L32
